name: Xposed
on:
  workflow_dispatch:
      inputs:
        cheat:
          description: "module name:"
          required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Zygisk-Azurlane
      uses: actions/checkout@v3
      with:
        repository: liusj5257/Zygisk-Azurlane
        token: ${{ secrets.TOKEN }}
        ref: main
        path: Zygisk-Azurlane
    - name: checkout xposed
      uses: actions/checkout@v3
      with:
        repository: liusj5257/Zygisk-Azurlane
        token: ${{ secrets.TOKEN }}
        ref: xposed
        path: xposed
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - name: build lib
      run: |
        chmod +x ./gradlew
        # if [[ ${{ github.event.inputs.cheat }} == 'true' ]]; then
        #   sed -i '/endif()/a add_definitions(-D CHEAT)' module/src/main/cpp/CMakeLists.txt
        # fi
        ./gradlew :module:assembleRelease
      working-directory: Zygisk-Azurlane
    - name: build xposed apk
      run: |
        chmod +x ./gradlew
        ./gradlew build
      working-directory: xposed
      
    - name: upload apk
      if: ${{ github.event.inputs.cheat }} != 'true'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Xposed"
        draft: true
        title: "Xposed"
        files: |
          xposed/output/*.apk

    - name: build lib
      run: |
        chmod +x ./gradlew
        sed -i '/endif()/a add_definitions(-D CHEAT)' module/src/main/cpp/CMakeLists.txt
        ./gradlew :module:assembleRelease
      working-directory: Zygisk-Azurlane
      
    - name: build xposed apk
      run: |
        chmod +x ./gradlew
        ./gradlew build
      working-directory: xposed

    - name: upload XposedCheat apk
      if: ${{ github.event.inputs.cheat }} == 'true'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "XposedCheat"
        draft: true
        title: "XposedCheat"
        files: |
          xposed/output/*.apk
